# Generated by Django 4.1.7 on 2023-03-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='book_available',
            new_name='stock_availability',
        ),
    ]
